In [9]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [10]:
ficoscores = np.random.randint(350,850,500)
ficoscores

array([482, 686, 471, 768, 800, 830, 368, 819, 688, 560, 411, 684, 829,
       617, 558, 534, 487, 833, 738, 846, 503, 404, 715, 785, 426, 385,
       506, 370, 839, 829, 363, 572, 367, 357, 755, 597, 556, 818, 489,
       790, 593, 676, 521, 604, 599, 633, 659, 402, 804, 574, 600, 525,
       676, 484, 780, 793, 738, 506, 606, 428, 765, 365, 739, 835, 744,
       679, 564, 739, 360, 808, 827, 510, 846, 499, 502, 585, 670, 559,
       558, 566, 655, 461, 441, 819, 461, 446, 370, 655, 477, 689, 827,
       568, 421, 569, 472, 358, 818, 667, 557, 364, 557, 416, 565, 662,
       705, 647, 822, 514, 835, 842, 359, 464, 540, 792, 613, 625, 438,
       399, 622, 816, 802, 815, 548, 422, 775, 437, 467, 507, 732, 678,
       361, 783, 362, 639, 695, 563, 586, 775, 597, 567, 495, 469, 668,
       418, 763, 656, 619, 798, 672, 392, 603, 779, 419, 740, 356, 641,
       511, 531, 546, 374, 799, 547, 435, 762, 555, 834, 635, 409, 718,
       573, 622, 576, 442, 630, 829, 525, 535, 365, 471, 373, 63

In [11]:
length_of_employment = np.random.uniform(low=0.0, high=5, size=500)
length_of_employment

array([ 1.33950148,  2.41166966,  3.42382162,  4.81382048,  2.36340719,
        3.80348149,  2.78811865,  0.00660748,  0.79377043,  0.75770903,
        2.84666118,  4.70166444,  2.86694188,  1.59138226,  4.2479103 ,
        1.24990357,  0.80206165,  1.94462954,  3.73162795,  4.37414927,
        0.45710256,  2.43496561,  1.30427143,  0.11593412,  4.01433156,
        4.12988526,  0.36298152,  1.35771719,  0.3716985 ,  1.28343449,
        0.14232083,  4.22905059,  0.44740463,  4.92524127,  2.60850191,
        2.26039893,  3.42739347,  0.53649617,  3.18536708,  4.10899303,
        2.78270414,  4.68437747,  4.67388158,  4.46999633,  4.82781356,
        1.02690573,  3.10759047,  0.70336368,  2.85047078,  0.13957367,
        2.15077244,  2.97403653,  3.23818375,  4.32060345,  0.415461  ,
        3.00085708,  0.55752942,  1.63008272,  4.63547143,  0.07602023,
        0.90434713,  2.17238848,  3.89650614,  4.71549286,  0.96545862,
        3.32091748,  0.79897288,  0.18972697,  0.39238268,  1.05

In [12]:
length_of_current_residency = np.random.uniform(low=0.0, high=3, size=500)
length_of_current_residency

array([  7.56560936e-01,   9.77482710e-01,   1.67976140e+00,
         3.38533177e-01,   8.78235814e-02,   1.08093515e+00,
         1.75979454e+00,   2.80202284e+00,   1.11328769e+00,
         1.52054553e+00,   1.39553293e+00,   1.27539309e+00,
         1.90158775e+00,   2.30382158e+00,   6.00005321e-01,
         2.36779635e+00,   7.20209306e-01,   1.77879561e+00,
         2.73569666e+00,   1.68133320e+00,   1.99571089e+00,
         2.69868873e-01,   2.38913531e+00,   8.60078061e-01,
         2.26478997e+00,   1.90911074e+00,   1.61304213e+00,
         4.53293034e-01,   2.61534743e+00,   1.78731977e+00,
         2.80456580e+00,   1.69539414e+00,   2.50643111e+00,
         2.12797963e+00,   2.09887901e+00,   1.31427549e+00,
         1.39976151e+00,   1.59035381e+00,   2.62749741e+00,
         6.03379147e-02,   4.88731534e-01,   1.25616150e+00,
         1.15914742e+00,   2.91976447e+00,   1.31782454e+00,
         1.04702600e+00,   1.54443901e+00,   5.58646635e-02,
         1.00555602e+00,

In [13]:
total_monthly_income = np.random.randint(2000,10000,500)
total_monthly_income

array([2710, 3262, 6730, 8641, 7916, 6377, 8814, 4181, 4499, 2465, 7771,
       5939, 8110, 5593, 2197, 3473, 4366, 4394, 3843, 6508, 2760, 2919,
       2942, 7038, 7839, 3901, 9401, 8777, 5965, 8244, 5356, 2029, 5561,
       5395, 3685, 6913, 7037, 6569, 5607, 7957, 2862, 8969, 7409, 6499,
       8352, 7509, 6123, 7049, 8917, 5962, 9318, 9984, 7198, 8256, 3614,
       8480, 3881, 8183, 2325, 7512, 5169, 2282, 4516, 3473, 3518, 4590,
       2208, 2727, 7440, 5521, 4723, 3041, 3084, 7987, 4571, 4631, 2205,
       9893, 2696, 8120, 8907, 7562, 7943, 8514, 2567, 3776, 7110, 5027,
       7929, 3430, 4410, 8545, 4828, 3761, 3193, 5973, 5230, 5312, 8845,
       5175, 9407, 2724, 6258, 4960, 8833, 9652, 8822, 4163, 5360, 9820,
       3724, 4760, 5590, 9910, 6602, 4954, 2173, 8304, 4204, 9054, 3967,
       3991, 6611, 7867, 5629, 3832, 4964, 3678, 8650, 2595, 6489, 7800,
       3423, 4489, 9488, 6317, 3981, 3347, 6006, 2176, 5271, 5732, 3282,
       7853, 9716, 8672, 2821, 8319, 6416, 4935, 51

In [14]:
debt_to_income_ratio = np.random.uniform(low=0.0, high=1, size=500)
debt_to_income_ratio

array([ 0.81362074,  0.67808776,  0.93207644,  0.01841429,  0.14919721,
        0.79840085,  0.49657789,  0.47359305,  0.45621807,  0.96348187,
        0.69276314,  0.0355289 ,  0.18520528,  0.41485269,  0.00978357,
        0.63094304,  0.77571729,  0.39473309,  0.6801868 ,  0.20813922,
        0.95197278,  0.30261715,  0.76953973,  0.22113581,  0.2832096 ,
        0.59589094,  0.51422771,  0.64325199,  0.95873474,  0.94145748,
        0.55090111,  0.98673166,  0.97449433,  0.9906508 ,  0.50442097,
        0.73989108,  0.81639988,  0.44940263,  0.37294548,  0.62871642,
        0.90600022,  0.54650255,  0.2767228 ,  0.00702055,  0.2122875 ,
        0.92424899,  0.33015675,  0.23070083,  0.59196673,  0.49530778,
        0.32468652,  0.93586493,  0.42501189,  0.7209806 ,  0.10935298,
        0.21818363,  0.64475065,  0.2530075 ,  0.20266982,  0.47626398,
        0.71423708,  0.27101398,  0.22475068,  0.59261832,  0.16819226,
        0.93960286,  0.19148192,  0.59938805,  0.87527512,  0.83

In [20]:
main = pd.DataFrame(data=[ficoscores,length_of_employment,length_of_current_residency,total_monthly_income,debt_to_income_ratio]).T
main

0     1     2        3     4
0   482.000 1.340 0.757 2710.000 0.814
1   686.000 2.412 0.977 3262.000 0.678
2   471.000 3.424 1.680 6730.000 0.932
3   768.000 4.814 0.339 8641.000 0.018
4   800.000 2.363 0.088 7916.000 0.149
5   830.000 3.803 1.081 6377.000 0.798
6   368.000 2.788 1.760 8814.000 0.497
7   819.000 0.007 2.802 4181.000 0.474
8   688.000 0.794 1.113 4499.000 0.456
9   560.000 0.758 1.521 2465.000 0.963
10  411.000 2.847 1.396 7771.000 0.693
11  684.000 4.702 1.275 5939.000 0.036
12  829.000 2.867 1.902 8110.000 0.185
13  617.000 1.591 2.304 5593.000 0.415
14  558.000 4.248 0.600 2197.000 0.010
15  534.000 1.250 2.368 3473.000 0.631
16  487.000 0.802 0.720 4366.000 0.776
17  833.000 1.945 1.779 4394.000 0.395
18  738.000 3.732 2.736 3843.000 0.680
19  846.000 4.374 1.681 6508.000 0.208
20  503.000 0.457 1.996 2760.000 0.952
21  404.000 2.435 0.270 2919.000 0.303
22  715.000 1.304 2.389 2942.000 0.770
23  785.000 0.116 0.860 7038.000 0.221
24  426.000 4.014 2.265 7839.000 0.283
25  385.000 4.130 1.909 3901.000 0.596
26  506.000 0.363 1.613 9401.000 0.514
27  370.000 1.358 0.453 8777.000 0.643
28  839.000 0.372 2.615 5965.000 0.959
29  829.000 1.283 1.787 8244.000 0.941
..      ...   ...   ...      ...   ...
470 743.000 2.705 0.211 5044.000 0.616
471 532.000 4.972 2.988 9401.000 0.078
472 408.000 1.477 1.657 4172.000 0.288
473 514.000 4.600 0.693 4420.000 0.327
474 702.000 0.176 1.764 8720.000 0.718
475 375.000 0.288 1.736 8707.000 0.062
476 804.000 0.636 2.758 3934.000 0.414
477 556.000 2.846 0.048 2417.000 0.078
478 774.000 3.632 2.815 5695.000 0.886
479 516.000 0.370 2.108 5314.000 0.066
480 693.000 0.801 0.161 9161.000 0.986
481 511.000 1.155 2.130 7185.000 0.714
482 429.000 0.940 2.295 9851.000 0.551
483 362.000 0.621 2.406 5316.000 0.818
484 579.000 0.125 1.879 4322.000 0.642
485 502.000 2.381 0.558 2934.000 0.372
486 657.000 0.228 0.048 3735.000 0.939
487 811.000 0.304 0.576 5621.000 0.535
488 753.000 3.963 0.734 5268.000 0.259
489 818.000 4.287 1.935 5491.000 0.568
490 790.000 3.886 0.442 5617.000 0.614
491 789.000 3.162 1.264 5709.000 0.881
492 571.000 0.617 1.950 3077.000 0.213
493 523.000 4.052 2.166 5486.000 0.953
494 831.000 3.020 1.052 6000.000 0.762
495 630.000 1.796 1.227 4288.000 0.712
496 407.000 2.624 2.350 3185.000 0.373
497 497.000 4.827 0.243 8736.000 0.136
498 736.000 2.871 0.984 3350.000 0.297
499 412.000 4.693 0.041 3797.000 0.330

[500 rows x 5 columns]